### ISSUE TITLE
Feature req: Add sha1sums check field for boot-ISO http urls

### ISSUE THREAD

**Issue by rowanthorpe** [grnet/ganetimgr#38]
It would be nice if ganetimgr had an extra field in the instance boot-configuration, for specifying an sha1sum (which could be copy-pasted) to use to verify an ISO image when it's being booted from an http URL. If that's not always possible it could just be an optional field (skipping the check if empty). The local patches to ganeti-instance-image do this under the hood anyway, so it should be
trivially easy to implement in the UI, and would be _much_ safer against MITM attacks.

**Comment by alexkiousis** [comment]
I'm closing this.
This should be implemented in QEMU's layer (as a libcurl checksuming feature?). Ganetimgr doesn't touch anything on ganeti clusters.
