### ISSUE TITLE
Autofocus on important fields on templates

### ISSUE THREAD

**Issue by alexkiousis** [grnet/ganetimgr#41]
Autofocus keyboard input on important fields, i.e. username field on login and search on index.

**Comment by kroustou** [comment]
fixed in c0d6f4caea25869fdf7e6d75222701796051cdd8

**Comment by alexkiousis** [comment]
Autofocus on the main search bar too, pretty please :)

**Comment by kroustou** [comment]
This one is also fixed in the same commit. The input is focused as soon as the data on index has been loaded.
