### ISSUE TITLE
no dashes allowed in cluster names

### ISSUE THREAD

**Issue by sunweaver** [grnet/ganetimgr#43]
I just figured out what caused my Ganeti Mgr instance to crash on listing VMs under the Nodes submenu and the when clicking on Graphs -> Get Graphs .

The ganetimgr WebGUI does not like if the "cluster_slug" parameter of a Ganeti cluster contains the dash character ("-"). If a cluster_slug contains a slash, the UI (i.e., django) spits out this error message:

""" (when attempting to view cluster graphs)
NoReverseMatch at /graph/all/

Reverse for 'cluster-get-nodes-graphs' with arguments '()' and keyword arguments '{'cluster_slug': u'g-c_demo'}' not found.

Request Method: 	POST
Request URL: 	http://127.0.0.1:8088/graph/all/
Django Version: 	1.4.5
Exception Type: 	NoReverseMatch
Exception Value: 	

Reverse for 'cluster-get-nodes-graphs' with arguments '()' and keyword arguments '{'cluster_slug': u'g-c_demo'}' not found.

Exception Location: 	/usr/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 422
Python Executable: 	/usr/bin/python
Python Version: 	2.7.3
Python Path: 	

['/var/lib/ganetimgr/ganetimgr/ganetimgr',
 '/var/lib/ganetimgr/ganetimgr',
 '/usr/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7']

Server time: 	Wed, 6 May 2015 16:56:34 +0200
"""
When renaming the cluster_slug to something not containing a dash character, the WebUI renders the pages/views just fine.

**Comment by alexkiousis** [comment]
Hi,
we also saw that bug recently. For some reason ganeti's RAPI doesn't return any vm information but returns everything else (node info, jobs, etc).
We'll try to pinpoint it in the next days.

**Comment by kroustou** [comment]
Hello, fixed in 6566ac3c6728588e7ff5be4b9ea9a48f524c48ad. For more details look at urls.py.dist under ganetimgr directory.
