### ISSUE TITLE
locale folder with django-1.7

### ISSUE THREAD

**Issue by sunweaver** [grnet/ganetimgr#45]
Hi,

after a while I figured out that for Django 1.7 the locale folder needs to be moved into the ganeti/ subfolder (mv locale ganeti/) to work again.

See https://docs.djangoproject.com/en/dev/topics/i18n/translation/#how-django-discovers-translations

Mike

**Comment by kroustou** [comment]
Ok good to know, thanks! I will fix it as soon as i start working on django 1.7.

**Comment by ioparaskev** [comment]
Since we have a `LOCALE_PATHS` setting in the settings.py.dist, this is not needed since the setting provides a more generic way to place wherever you like the translations
