### ISSUE TITLE
What is used to generate collectd graphs?

### ISSUE THREAD

**Issue by ktims** [grnet/ganetimgr#50]
I can't find any documentation of what COLLECTD_URL is supposed to point to. I poked around at some of the collectd frontends I could find and none seem to have a matching URL format to what ganetimgr generates.

**Comment by alexkiousis** [comment]
Yeah, completely understandable. We use a custom python script to serve them.
I uploaded it along with sample configuration [ here ] (https://github.com/grnet/vima-grapher).

We run this on a separate host but there should be no problem running it along with ganetimgr.

Unfortunately there is no documentation. Also the collectd plugin only works with KVM VMs.

If you have any feedback. feel free to open an issue on the new repo.
