### ISSUE TITLE
Not changing back to English after selection of localized language in the web interface

### ISSUE THREAD

**Issue by salsa-dev** [grnet/ganetimgr#51]
Dear devs,

I'm testing v1.6.0 with localization to russian.

After changing language in the web interface to a localized one changing back to English doesn't work (nothing happens). The same actually happens with Greek.

**Comment by sergafts** [comment]
I am not sure why this is happening. In our production environment it I see no such behaviour.

**Comment by salsa-dev** [comment]
Unfortunately I don't know how to debug this issue. I have no logs on this at all.

**Comment by salsa-dev** [comment]
Changing settings.py to
```
LANGUAGES = (
    ('en', u'English'),
    ('ru', u'Russian'),
    ('el', u'Ελληνικά'),
)

LANGUAGE_CODE = 'ru'
```
And making a directory with translation files:
`ganetimgr/locale/en/LC_MESSAGES/django.*`
solves the problem.
