### ISSUE TITLE
display instance disk-template type 

### ISSUE THREAD

**Issue by isrc** [grnet/ganetimgr#53]
Hi,
In the details page of an instance, could you please add a field displaying the disk-template type (plain, drbd...) of an instance ? 
Right now, it seems that there's no way to get that information within ganetimgr 

Thanks !

**Comment by sergafts** [comment]
This is already implemented in the master branch, in commit d641fdf6744336a2e639930ca2f067edf66d4932

**Comment by isrc** [comment]
Oops, my bad: i should have checked master ! Thanks Sergios !
